export const LangPack = {
    en: {
        actions: 'Actions',
        add: 'Add',
        all: 'All',
        attention: 'Attention',
        back: 'Back',
        cancel: 'Cancel',
        close: 'Close',
        content: 'Content',
        create: 'Create',
        сreateareminder: 'Create a reminder',
        createreminder: 'Create reminder',
        creation: 'Creation',
        creationdate: 'Creation date',
        creationdatefrom: 'Creation date (from)',
        creationdateto: 'Creation date (to)',
        сurrent: 'Current',
        daysago: 'days ago',
        delete: 'Delete',
        deleteall: 'Delete all',
        deleteselected: 'Delete selected',
        detachall: 'Detach all',
        errorcreateanewnotification: 'An error occurred while attempting to create a new notification',
        filters: 'Filters',
        hago: 'h. ago',
        justnow: 'just now',
        markallasread: 'Mark all as read',
        markallasunread: 'Mark all as unread',
        markselectedasread: 'Mark selected (*) as read',
        markselectedasunread: 'Mark selected (*) as unread',
        minago: 'min. ago',
        newnotification: 'New notification',
        notifications: 'Notifications',
        operationsoneveryone: 'Operations on everyone',
        operationsonselecteditems: 'Operations on selected items',
        operationsuccessful: 'Operation successful',
        pin: 'Pin',
        pinall: 'Pin all',
        read: 'Read',
        reminders: 'Reminders',
        requiredfieldsaremissing: 'Required fields are missing',
        selectall: 'Select all',
        selected: 'Selected',
        showmore: 'Show more',        
        startapp: 'Start App',
        statistics: 'Statistics',
        status: 'Status',
        tabs: 'Tabs',
        title: 'Title',
        totalnotifications: 'Total notifications',
        type: 'Type',
        unpin: 'Unpin',
        unread: 'Unread'
    },
    ru: {
        actions: 'Действия',        
        add: 'Добавить',
        all: 'Все',
        attention: 'Внимание',
        back: 'Назад',
        cancel: 'Отмена',
        close: 'Закрыть',
        content: 'Содержание',
        create: 'Создать',
        сreateareminder: 'Создать напоминание',
        createreminder: 'Создание напоминания',
        creation: 'Создание',
        creationdate: 'Дата создания',
        creationdatefrom: 'Дата создания (от)',
        creationdateto: 'Дата создания (до)',
        сurrent: 'Актуальные',
        daysago: 'дн. назад',
        delete: 'Удалить',
        deleteall: 'Удалить все',
        deleteselected: 'Удалить выбранные',
        detachall: 'Открепить все',
        errorcreateanewnotification: 'Произошла ошибка при попытке создать новое уведомление',
        filters: 'Фильтры',
        hago: 'ч. назад',
        justnow: 'только что',
        markallasread: 'Отметить все как прочитанные',
        markallasunread: 'Отметить все как не прочитанные',
        markselectedasread: 'Отметить выбранные (*) как прочитанное',
        markselectedasunread: 'Отметить выбранные (*) как не прочитанное',
        minago: 'мин. назад',
        newnotification: 'Новое уведомление',
        notifications: 'Уведомления',
        operationsoneveryone: 'Операции над всеми',
        operationsonselecteditems: 'Операции над выбранными',
        operationsuccessful: 'Операция прошла успешно',
        pin: 'Закрепить',
        pinall: 'Закрепить все',
        reminders: 'Напоминания',
        read: 'Прочитанные',
        requiredfieldsaremissing: 'Обязательные поля не заполнены',
        selectall: 'Выбрать все',
        selected: 'Выбрано',
        showmore: 'Показать полностью',
        startapp: 'Запуск приложения',
        statistics: 'Статистика',
        status: 'Статус',
        tabs: 'Вкладки',
        title: 'Заголовок',
        totalnotifications: 'Всего уведомлений',
        type: 'Тип',
        unpin: 'Открепить',
        unread: 'Непрочитанные',
    },
};