export const LangPack = {
    en: {
        appname: 'MPlayer',
        add: 'Add',
        totaltracks: 'Total tracks',
        duration: 'Duration',
        prevtrack: 'Previous track',
        stopplayback: 'Stop playback',
        pause: 'Pause',
        play: 'Play',
        nexttrack: 'Next track',
        artist: 'Artist',
        album: 'Album',
        genre: 'Genre',
        name: 'Name',
        min: 'Min.',
        chooseanother: 'Choose another',
        year: 'Year',
        trackinalbum: 'Track in the album',
        rating: 'Rating',
        lyrics: 'Lyrics',
        cover: 'Cover',
        abouttrack: 'About track',
    },
    ru: {
        appname: 'MPlayer',
        add: 'Добавить',
        totaltracks: 'Треков всего',
        duration: 'Продолжительность',
        prevtrack: 'Предыдущий трек',
        stopplayback: 'Остановить воспроизведение',
        pause: 'Пауза',
        play: 'Воспроизвести',
        nexttrack: 'Следующий трек',
        artist: 'Исполнитель',
        album: 'Альбом',
        genre: 'Жанр',
        name: 'Название',
        min: 'Mин.',
        chooseanother: 'Выбрать другое',
        year: 'Год',
        trackinalbum: 'Трек в альбоме',
        rating: 'Рейтинг',
        lyrics: 'Текст песни',
        cover: 'Обложка',
        abouttrack: 'О треке',
    },
};