export const LangPack = {
    en: {
        description: 'Description',
        name: 'Name',
        version: 'Version',
        accounts: 'Accounts',
        design: 'Design',
        desktopbgimg: 'Desktop background image',
        memmanagment: 'Memory management',
        clear: 'Clear',
        delquest: 'Delete data from ',
        select: 'Select',
        date: 'Date',
        collapse: 'Collapse',
        created: 'Created',
        changed: 'Changed',
        login: 'Login',
        user: 'User',
        allsettings: 'All settings',
        idbMemory: 'Memory',
        idbTables: 'Tables',
        idbRecords: 'Records',
        idbDatabase: 'Database',
        idbSchemaVersion: 'Schema version',
        idbDataVersion: 'Data version',
        idbEstimatedSize: 'Estimated size (OSIDB)',
        idbOccupiedMB: 'Used (MB)',
        idbOccupiedPercent: 'Used (%)',
        idbNoData: 'No data',
        idbLoading: 'Loading...',
        idbRefresh: 'Refresh',
        idbOriginLimit: 'Origin quota',
        idbOriginUsed: 'Origin used',
    },
    ru: {
        description: 'Описание',
        name: 'Наименование',
        version: 'Версия',
        accounts: 'Учетные записи',
        design: 'Оформление',
        desktopbgimg: 'Фоновое изображение рабочего стола',
        memmanagment: 'Управление памятью',
        clear: 'Очистить',
        delquest: 'Удалить данные из ',
        select: 'Выбрать',
        date: 'Дата',
        collapse: 'Свернуть',
        created: 'Создано',
        changed: 'Изменено',
        login: 'Логин',
        user: 'Пользователь',
        allsettings: 'Все настройки',
        idbMemory: 'Память',
        idbTables: 'Таблицы',
        idbRecords: 'Записей',
        idbDatabase: 'База данных',
        idbSchemaVersion: 'Версия схемы',
        idbDataVersion: 'Версия данных',
        idbEstimatedSize: 'Оценочный размер (OSIDB)',
        idbOccupiedMB: 'Занято (в MB)',
        idbOccupiedPercent: 'Занято (в %)',
        idbNoData: 'Нет данных',
        idbLoading: 'Загрузка...',
        idbRefresh: 'Обновить',
        idbOriginLimit: 'Лимит (origin)',
        idbOriginUsed: 'Занято (origin)',
    },
};