export const LangPack = {
    en: {
        attenttextone: 'All data associated with the selected account stored on this device will be deleted.',
        attenttexttwo: 'It will be impossible to restore your account!',
        beginningtext: 'To get started, please select an account.',
        cancel: 'Cancel',
        choose: 'Choose',
        createanewone: 'Create a new one',
        createanewaccount: 'Create a new account.',
        createanaccount: 'Create an account',
        delete: 'Delete',
        deleteaccount: 'Delete account',
        enteryourpassword: 'Enter your password',
        login: 'Login',
        logintoyouraccount: 'Login to your account',
        password: 'Password',
        pleasenote: 'Please note',
        selectanavatar: 'Select an avatar',
        yourlogin: 'Your Login',
        yourpassword: 'Your Password',
        yourpasswordoptional: 'Your password (optional)',
    },
    ru: {
        attenttextone: 'Все данные, связанные с выбранной учетной записью, хранящиеся на данном устройстве, будут удалены.',
        attenttexttwo: 'Восстановить учетную запись будет невозможно!',
        beginningtext: 'Для начала работы выберите учетную запись.',
        cancel: 'Отмена',
        choose: 'Выбрать',
        createanewone: 'Создать новую',
        createanewaccount: 'Создать новую учетную запись',
        createanaccount: 'Создать учетную запись',
        delete: 'Удалить',
        deleteaccount: 'Удалить учетную запись',
        enteryourpassword: 'Введите пароль',
        login: 'Войти',
        logintoyouraccount: 'Вход в учетную запись',
        password: 'Пароль',
        pleasenote: 'Обратите внимание',
        selectanavatar: 'Выберите аватар',
        yourlogin: 'Ваш логин',
        yourpassword: 'Ваш пароль',
        yourpasswordoptional: 'Ваш пароль (не обязательно)',        
    },
};