export const LangPack = {
    en: {
        clearlist: 'Clear list',
        clearviewinglist: 'Clear viewing list',
        date: 'Date',
        decrease: 'Decrease',
        filename: 'File name',
        imageproperties: 'Image properties',
        increase: 'Increase',
        loading: 'Loading',
        nextimage: 'Next image',
        noimagesopen: 'No images open',
        open: 'Open',
        openimage: 'Open image',
        originalsize: 'Original size',
        previousimage: 'Previous image',
        properties: 'Properties',
        selectfile: 'Select file',
        size: 'Size',
        type: 'Type',
        volume: 'Volume',
    },
    ru: {
        clearlist: 'Очистить список',
        clearviewinglist: 'Очистить список для просмотра',
        date: 'Дата',
        decrease: 'Уменьшить',
        filename: 'Имя файла',
        imageproperties: 'Свойства изображения',
        increase: 'Увеличить',
        loading: 'Загрузка',
        nextimage: 'Следующее изображение',
        noimagesopen: 'Нет открытых изображений',
        open: 'Открыть',
        openimage: 'Открыть изображение',
        originalsize: 'Оригинальный размер',
        previousimage: 'Предыдущее изображение',
        properties: 'Свойства',
        selectfile: 'Выбрать файл',
        size: 'Размер',
        type: 'Тип',
        volume: 'Объем',
    },
};