export const LangPack = {
    en: {
        all: 'All',
        audio: 'Audio',
        created: 'Created',
        createdAt: 'Created',
        createnewfolder: 'Create new folder',
        displayfilter: 'Display filter',
        documents: 'Documents',
        enterfoldername: 'Enter folder name',
        extension: 'Extension',
        folderisempty: 'Folder is empty',
        home: 'Home',
        images: 'Images',
        items: 'items',
        mimetype: 'Media type',
        modified: 'Modified',
        name: 'Name',
        newfolder: 'New Folder',
        private: 'Private',
        protected: 'Protected',
        root: 'Root',
        size: 'Size',
        text: 'Text',
        type: 'Type',
        typefilearchive: 'Archive',
        typefileaudion: 'Audio file',
        typefilefile: 'File',
        typefilefolder: 'Folder',
        typefileimage: 'Image',
        typefilevideo: 'Video file',
        updated: 'Updated',
        updatedAt: 'Updated',
        upload: 'Upload',
        uploadfile: 'Upload file',        
    },
    ru: {
        all: 'Все',
        audio: 'Аудио',
        created: 'Создано',
        createdAt: 'Создано',
        createnewfolder: 'Создать папку',
        displayfilter: 'Фильтр отображения',
        documents: 'Документы',
        enterfoldername: 'Введите имя папки',
        extension: 'Разширение',
        folderisempty: 'Папка пуста',
        home: 'Дом',
        images: 'Изображения',
        items: 'эл.',
        mimetype: 'MIME-тип',
        modified: 'Изменён',
        name: 'Имя',
        newfolder: 'Новая папка',
        private: 'Личный',
        protected: 'Защищенный',
        root: 'Корень',
        size: 'Размер',
        text: 'Текст',
        type: 'Тип',
        typefilearchive: 'Архив',
        typefileaudion: 'Аудио файл',
        typefilefile: 'Файл',
        typefilefolder: 'Папка',
        typefileimage: 'Изображение',
        typefilevideo: 'Видео файл',
        updated: 'Изменено',
        updatedAt: 'Обновлено',
        upload: 'Загрузить',
        uploadfile: 'Загрузить файл',
    },
};