export const LangPack = {
    en: {
        audio: 'Audio',
        upload: 'Upload',
        uploadfile: 'Upload file',
        newfolder: 'New Folder',
        root: 'Root',
        documents: 'Documents',
        items: 'items',
        empty: 'Folder is empty',
        enter_folder_name: 'Enter folder name:',
        root_tooltip: 'Go to root',
        back_tooltip: 'Go back',
        upload_tooltip: 'Upload files',
        createnewfolder: 'Create new folder',
        grid_view: 'Grid view',
        list_view: 'List view',
        name: 'Name',
        size: 'Size',
        modified: 'Modified',
        type: 'Type',
        text: 'Text',
        images: 'Images',
        home: 'Home',
    },
    ru: {
        audio: 'Аудио',
        upload: 'Загрузить',
        uploadfile: 'Загрузить файл',
        newfolder: 'Новая папка',
        root: 'Корень',
        documents: 'Документы',
        items: 'эл.',
        empty: 'Папка пуста',
        enter_folder_name: 'Введите имя папки:',
        root_tooltip: 'Перейти в корень',
        back_tooltip: 'Назад',
        upload_tooltip: 'Загрузить файлы',
        createnewfolder: 'Создать папку',
        grid_view: 'Плитка',
        list_view: 'Список',
        name: 'Имя',
        size: 'Размер',
        modified: 'Изменён',
        type: 'Тип',
        text: 'Текст',
        images: 'Изображения',
        home: 'Дом',
    },
};